NSE_STOCKS = {
    "Reliance Industries": "RELIANCE.NS",
    "TCS": "TCS.NS",
    "HDFC Bank": "HDFCBANK.NS",
    "Infosys": "INFY.NS",
    "ICICI Bank": "ICICIBANK.NS",
    "Hindustan Unilever": "HINDUNILVR.NS",
    "ITC": "ITC.NS",
    "Kotak Mahindra Bank": "KOTAKBANK.NS",
    "Larsen & Toubro": "LT.NS",
    "Axis Bank": "AXISBANK.NS",
    "Bajaj Finance": "BAJFINANCE.NS",
    "Asian Paints": "ASIANPAINT.NS",
    "Wipro": "WIPRO.NS",
    "HCL Technologies": "HCLTECH.NS",
    "Maruti Suzuki": "MARUTI.NS",
    "Sun Pharma": "SUNPHARMA.NS",
    "Titan Company": "TITAN.NS",
    "Tech Mahindra": "TECHM.NS",
    "Nestle India": "NESTLEIND.NS",
    "Power Grid": "POWERGRID.NS",
    "NTPC": "NTPC.NS",
    "Adani Enterprises": "ADANIENT.NS",
    "Adani Ports": "ADANIPORTS.NS",
    "Adani Green": "ADANIGREEN.NS",
    "Adani Power": "ADANIPOWER.NS",
    "JSW Steel": "JSWSTEEL.NS",
    "Tata Steel": "TATASTEEL.NS",
    "Tata Motors": "TATAMOTORS.NS",
    "Tata Consultancy": "TCS.NS",
    "Tata Power": "TATAPOWER.NS",
    "Bajaj Auto": "BAJAJ-AUTO.NS",
    "Bajaj Finserv": "BAJAJFINSV.NS",
    "UltraTech Cement": "ULTRACEMCO.NS",
    "Grasim Industries": "GRASIM.NS",
    "IndusInd Bank": "INDUSINDBK.NS",
    "SBI": "SBIN.NS",
    "Bank of Baroda": "BANKBARODA.NS",
    "Punjab National Bank": "PNB.NS",
    "Canara Bank": "CANBK.NS",
    "ONGC": "ONGC.NS",
    "Coal India": "COALINDIA.NS",
    "BPCL": "BPCL.NS",
    "IOC": "IOC.NS",
    "Cipla": "CIPLA.NS",
    "Dr Reddys": "DRREDDY.NS",
    "Divi's Labs": "DIVISLAB.NS",
    "Apollo Hospitals": "APOLLOHOSP.NS",
    "Eicher Motors": "EICHERMOT.NS",
    "Hero MotoCorp": "HEROMOTOCO.NS",
    "Bharat Electronics": "BEL.NS",
    "HAL": "HAL.NS",
    "Siemens India": "SIEMENS.NS",
    "ABB India": "ABB.NS",
    "Havells India": "HAVELLS.NS",
    "Pidilite Industries": "PIDILITIND.NS",
    "Berger Paints": "BERGEPAINT.NS",
    "Dabur India": "DABUR.NS",
    "Marico": "MARICO.NS",
    "Britannia": "BRITANNIA.NS",
    "Godrej Consumer": "GODREJCP.NS",
    "Colgate": "COLPAL.NS",
    "Avenue Supermarts": "DMART.NS",
    "Trent": "TRENT.NS",
    "Varun Beverages": "VBL.NS",
    "United Spirits": "MCDOWELL-N.NS",
    "Zomato": "ZOMATO.NS",
    "Nykaa": "NYKAA.NS",
    "Paytm": "PAYTM.NS",
    "Delhivery": "DELHIVERY.NS",
    "PB Fintech": "POLICYBZR.NS",
    "Nazara Technologies": "NAZARA.NS",
    "Info Edge": "NAUKRI.NS",
    "Just Dial": "JUSTDIAL.NS",
    "Persistent Systems": "PERSISTENT.NS",
    "Mphasis": "MPHASIS.NS",
    "Coforge": "COFORGE.NS",
    "LTIMindtree": "LTIM.NS",
    "Zensar Technologies": "ZENSARTECH.NS",
    "Hexaware": "HEXAWARE.NS",
    "Indraprastha Gas": "IGL.NS",
    "Mahanagar Gas": "MGL.NS",
    "Gujarat Gas": "GUJGASLTD.NS",
    "Petronet LNG": "PETRONET.NS",
    "Interglobe Aviation": "INDIGO.NS",
    "SpiceJet": "SPICEJET.NS",
    "Container Corp": "CONCOR.NS",
    "Blue Dart": "BLUEDART.NS",
    "SRF": "SRF.NS",
    "PI Industries": "PIIND.NS",
    "UPL": "UPL.NS",
    "Coromandel International": "COROMANDEL.NS",
    "Chambal Fertilizers": "CHAMBLFERT.NS",
    "Tata Chemicals": "TATACHEM.NS",
    "Aarti Industries": "AARTIIND.NS",
    "Deepak Nitrite": "DEEPAKNTR.NS",
    "Laurus Labs": "LAURUSLABS.NS",
    "Alkem Labs": "ALKEM.NS",
    "Torrent Pharma": "TORNTPHARM.NS",
    "Ipca Labs": "IPCALAB.NS",
    "Biocon": "BIOCON.NS",
    "Lupin": "LUPIN.NS",
    "Aurobindo Pharma": "AUROPHARMA.NS",
    "Glenmark Pharma": "GLENMARK.NS",
}

# Reverse lookup: ticker -> company name
TICKER_TO_COMPANY = {v: k for k, v in NSE_STOCKS.items()}

import requests
import pandas as pd

def fetch_all_nse_stocks():
    """Fetch complete NSE stock list dynamically."""
    try:
        url = "https://archives.nseindia.com/content/equities/EQUITY_L.csv"
        headers = {"User-Agent": "Mozilla/5.0"}
        df = pd.read_csv(url, storage_options={"headers": headers})
        stocks = {}
        for _, row in df.iterrows():
            name = str(row["NAME OF COMPANY"]).strip().title()
            ticker = str(row["SYMBOL"]).strip() + ".NS"
            stocks[name] = ticker
        return stocks
    except:
        return NSE_STOCKS  # fallback to hardcoded list